version: '3.8'
services:
  app:
    container_name: 'nest'
    build: .
    ports:
      - 3000:3000
    restart: always
    environment:
      POSTGRES_HOST: db
    links:
      - db
  app-migrations:
    container_name: 'migrations'
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm run migrations:run"
    links:
      - db
  db:
    container_name: postgres
    image: postgres:13.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: user
      POSTGRES_DB: db-test
      PGADMIN_LISTEN_ADDRESS: 127.0.0.1
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./artas/pg_data:/var/lib/postgresql/data/pgdata
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: m.s.kopyl.kharkov@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - 80:80
